In [1]:
print("hello wec")

hello wec

first thing is importing the data 
i have chosen the movielens data 
let see how the data looks

In [6]:
import pandas as pd
df = pd.read_csv(
    'ml-100k/u.data', 
    sep='\t', 
    header=None, 
    names=['user_id', 'item_id', 'rating', 'timestamp']
)

In [7]:
df

       user_id  item_id  rating  timestamp
0          196      242       3  881250949
1          186      302       3  891717742
2           22      377       1  878887116
3          244       51       2  880606923
4          166      346       1  886397596
...        ...      ...     ...        ...
99995      880      476       3  880175444
99996      716      204       5  879795543
99997      276     1090       1  874795795
99998       13      225       2  882399156
99999       12      203       3  879959583

[100000 rows x 4 columns]

checking the data

In [14]:
df.head()
# df.tail()
df.isnull().sum() # so there are no null values

user_id      0
item_id      0
rating       0
timestamp    0
dtype: int64

In [18]:
user_item_matrix = df.pivot(index='user_id', columns='item_id', values='rating').fillna(0)
# print(user_item_matrix.shape) 
# print(user_item_matrix.head())
user_item_matrix.head()

item_id,1,2,3,4,5,6,7,8,9,10,...,1673,1674,1675,1676,1677,1678,1679,1680,1681,1682
user_id,,,,,,,,,,,,,,,,,,,,,
1,5.0,3.0,4.0,3.0,3.0,5.0,4.0,1.0,5.0,3.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,4.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
5,4.0,3.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

what the above tabel means is that on one user id or a user how many movies it has watched and rated and rating 0 means it hasent seen or rated on it

In [24]:
from sklearn.model_selection import train_test_split
train_data, test_data = train_test_split(df,test_size=0.2, random_state=42)
train_data
test_data

       user_id  item_id  rating  timestamp
75721      877      381       4  882677345
80184      815      602       3  878694269
19864       94      431       4  891721716
76699      416      875       2  876696938
92991      500      182       2  883873556
...        ...      ...     ...        ...
32595       72      591       5  880035708
29313      523      393       5  883702411
37862      606      287       4  880921656
53421      650      612       4  891369656
42410      303       72       3  879485111

[20000 rows x 4 columns]

In [25]:
train_user_item_matrix = train_data.pivot(index='user_id', columns='item_id', values='rating').fillna(0)

In [27]:
train_user_item_matrix
test_data

       user_id  item_id  rating  timestamp
75721      877      381       4  882677345
80184      815      602       3  878694269
19864       94      431       4  891721716
76699      416      875       2  876696938
92991      500      182       2  883873556
...        ...      ...     ...        ...
32595       72      591       5  880035708
29313      523      393       5  883702411
37862      606      287       4  880921656
53421      650      612       4  891369656
42410      303       72       3  879485111

[20000 rows x 4 columns]